export const countries: any = [
    {
        label: "India",
        value: "hi_IN"
    }, {
        label: "United Arab Emirates",
        value: "ar_AE"
    }, {
        label: "Jordan",
        value: "ar_JO"
    }, {
        label: "Syria",
        value: "ar_SY"
    }, {
        label: "Croatia",
        value: "hr_HR"
    }, {
        label: "Belgium",
        value: "fr_BE"
    }, {
        label: "Panama",
        value: "es_PA"
    }, {
        label: "Malta",
        value: "mt_MT"
    }, {
        label: "Venezuela",
        value: "es_VE"
    }, {
        label: "",
        value: "bg"
    }, {
        label: "Taiwan",
        value: "zh_TW"
    }, {
        label: "Denmark",
        value: "da_DK"
    }, {
        label: "Puerto Rico",
        value: "es_PR"
    }, {
        label: "Vietnam",
        value: "vi_VN"
    }, {
        label: "United States",
        value: "en_US"
    }, {
        label: "Montenegro",
        value: "sr_ME"
    }, {
        label: "Sweden",
        value: "sv_SE"
    }, {
        label: "Bolivia",
        value: "es_BO"
    }, {
        label: "Singapore",
        value: "en_SG"
    }, {
        label: "Bahrain",
        value: "ar_BH"
    }, {
        label: "Saudi Arabia",
        value: "ar_SA"
    }, {
        label: "Yemen",
        value: "ar_YE"
    }, {
        label: "Malta",
        value: "en_MT"
    }, {
        label: "Finland",
        value: "fi_FI"
    }, {
        label: "Bosnia and Herzegovina",
        value: "sr_BA_#Latn"
    }, {
        label: "Ukraine",
        value: "uk_UA"
    }, {
        label: "Switzerland",
        value: "fr_CH"
    }, {
        label: "Argentina",
        value: "es_AR"
    }, {
        label: "Egypt",
        value: "ar_EG"
    }, {
        label: "Japan",
        value: "ja_JP_JP_#u-ca-japanese"
    }, {
        label: "El Salvador",
        value: "es_SV"
    }, {
        label: "Brazil",
        value: "pt_BR"
    }, {
        label: "Iceland",
        value: "is_IS"
    }, {
        label: "Czech Republic",
        value: "cs_CZ"
    }, {
        label: "Poland",
        value: "pl_PL"
    }, {
        label: "Spain",
        value: "ca_ES"
    }, {
        label: "Serbia and Montenegro",
        value: "sr_CS"
    }, {
        label: "Malaysia",
        value: "ms_MY"
    }, {
        label: "Spain",
        value: "es_ES"
    }, {
        label: "Colombia",
        value: "es_CO"
    }, {
        label: "Bulgaria",
        value: "bg_BG"
    }, {
        label: "Bosnia and Herzegovina",
        value: "sr_BA"
    }, {
        label: "Paraguay",
        value: "es_PY"
    }, {
        label: "Ecuador",
        value: "es_EC"
    }, {
        label: "United States",
        value: "es_US"
    }, {
        label: "Sudan",
        value: "ar_SD"
    }, {
        label: "Romania",
        value: "ro_RO"
    }, {
        label: "Philippines",
        value: "en_PH"
    }, {
        label: "Tunisia",
        value: "ar_TN"
    }, {
        label: "Montenegro",
        value: "sr_ME_#Latn"
    }, {
        label: "Guatemala",
        value: "es_GT"
    }, {
        label: "South Korea",
        value: "ko_KR"
    }, {
        label: "Cyprus",
        value: "el_CY"
    }, {
        label: "Mexico",
        value: "es_MX"
    }, {
        label: "Russia",
        value: "ru_RU"
    }, {
        label: "Honduras",
        value: "es_HN"
    }, {
        label: "Hong Kong",
        value: "zh_HK"
    }, {
        label: "Norway",
        value: "no_NO_NY"
    }, {
        label: "Hungary",
        value: "hu_HU"
    }, {
        label: "Thailand",
        value: "th_TH"
    }, {
        label: "Iraq",
        value: "ar_IQ"
    }, {
        label: "Chile",
        value: "es_CL"
    }, {
        label: "Morocco",
        value: "ar_MA"
    }, {
        label: "Ireland",
        value: "ga_IE"
    }, {
        label: "Turkey",
        value: "tr_TR"
    }, {
        label: "Estonia",
        value: "et_EE"
    }, {
        label: "Qatar",
        value: "ar_QA"
    }, {
        label: "Portugal",
        value: "pt_PT"
    }, {
        label: "Luxembourg",
        value: "fr_LU"
    }, {
        label: "Oman",
        value: "ar_OM"
    }, {
        label: "Albania",
        value: "sq_AL"
    }, {
        label: "Dominican Republic",
        value: "es_DO"
    }, {
        label: "Cuba",
        value: "es_CU"
    }, {
        label: "New Zealand",
        value: "en_NZ"
    }, {
        label: "Serbia",
        value: "sr_RS"
    }, {
        label: "Switzerland",
        value: "de_CH"
    }, {
        label: "Uruguay",
        value: "es_UY"
    }, {
        label: "Greece",
        value: "el_GR"
    }, {
        label: "Israel",
        value: "iw_IL"
    }, {
        label: "South Africa",
        value: "en_ZA"
    }, {
        label: "Thailand",
        value: "th_TH_TH_#u-nu-thai"
    }, {
        label: "France",
        value: "fr_FR"
    }, {
        label: "Austria",
        value: "de_AT"
    }, {
        label: "Norway",
        value: "no_NO"
    }, {
        label: "Australia",
        value: "en_AU"
    }, {
        label: "Netherlands",
        value: "nl_NL"
    }, {
        label: "Canada",
        value: "fr_CA"
    }, {
        label: "Latvia",
        value: "lv_LV"
    }, {
        label: "Luxembourg",
        value: "de_LU"
    }, {
        label: "Costa Rica",
        value: "es_CR"
    }, {
        label: "Kuwait",
        value: "ar_KW"
    }, {
        label: "Libya",
        value: "ar_LY"
    }, {
        label: "Switzerland",
        value: "it_CH"
    }, {
        label: "Germany",
        value: "de_DE"
    }, {
        label: "Algeria",
        value: "ar_DZ"
    }, {
        label: "Slovakia",
        value: "sk_SK"
    }, {
        label: "Lithuania",
        value: "lt_LT"
    }, {
        label: "Italy",
        value: "it_IT"
    }, {
        label: "Ireland",
        value: "en_IE"
    }, {
        label: "Singapore",
        value: "zh_SG"
    }, {
        label: "Canada",
        value: "en_CA"
    }, {
        label: "Belgium",
        value: "nl_BE"
    }, {
        label: "China",
        value: "zh_CN"
    }, {
        label: "Japan",
        value: "ja_JP"
    }, {
        label: "Greece",
        value: "de_GR"
    }, {
        label: "Serbia",
        value: "sr_RS_#Latn"
    }, {
        label: "India",
        value: "en_IN"
    }, {
        label: "Lebanon",
        value: "ar_LB"
    }, {
        label: "Nicaragua",
        value: "es_NI"
    }, {
        label: "Macedonia",
        value: "mk_MK"
    }, {
        label: "Belarus",
        value: "be_BY"
    }, {
        label: "Slovenia",
        value: "sl_SI"
    }, {
        label: "Peru",
        value: "es_PE"
    }, {
        label: "Indonesia",
        value: "in_ID"
    }, {
        label: "United Kingdom",
        value: "en_GB"
    }];

